(require 'rust-mode)
(setq rust-format-on-save t)
(setq racer-cmd (concat my/home-dir ".cargo/bin/racer"))

(add-hook 'rust-mode-hook  'my/common-programming-hook)
(add-hook 'rust-mode-hook  #'racer-mode)
(add-hook 'racer-mode-hook #'eldoc-mode)
(add-hook 'racer-mode-hook #'company-mode)
(add-hook 'flycheck-mode-hook #'flycheck-rust-setup)
;;(define-key rust-mode-map (kbd "TAB") #'company-indent-or-complete-common)
(setq company-tooltip-align-annotations t)
