dotfiles_dir = "repos/personal/dot-files"

[settings]
vars = [ "vars.toml" ]

[settings.dots]
fish = { source = "fish", target = ".config/fish" }
git = { source = "git/gitconfig", target = ".gitconfig", vars = "git/vars.toml" }
helix = { source = "helix", target = ".config/helix" }
kitty = { source = "kitty", target = ".config/kitty" }

[profiles.linux_laptop.dots]
kanata = { source = "linux/kanata", target = ".config/kanata" }
kanata_service = { source = "linux/kanata.service", target = ".config/systemd/user/kanata.service" }
# Wayland stuff
hypr = { source = "linux/hypr", target = ".config/hypr" }
sway = { source = "linux/sway", target = ".config/sway" }
waybar = { source = "linux/waybar", target = ".config/waybar" }
