dotfiles_dir = "repos/personal/dot-files"

[settings]
# vars = [ "vars.toml" ]

# posthooks = [ "sway reload" ]

[settings.dots]
fish = { source = "fish", target = ".config/fish" }
hypr = { source = "hypr", target = ".config/hypr" }
kanata = { source = "kanata", target = ".config/kanata" }
