dotfiles_dir = "repos/personal/dot-files"

[settings]
vars = [ "vars.toml" ]

[settings.dots]
emacs = { source = "emacs.d", target = ".emacs.d" }
fish = { source = "fish", target = ".config/fish" }
git = { source = "git/gitconfig", target = ".gitconfig", vars = "git/vars.toml" }

[profiles.linux_laptop.dots]
hypr = { source = "hypr", target = ".config/hypr" }
kanata = { source = "kanata", target = ".config/kanata" }
kanata_service = { source = "kanata.service", target = ".config/systemd/user/kanata.service" }
waybar = { source = "waybar", target = ".config/waybar" }
