default: catch

catch:
	@echo "Options:\n * install\n * check-changes"

install:
	@if [ ! -x ~/.emacs ]; then \
            cp dot.emacs ~/.emacs; \
        else \
            diff -ub dot.emacs ~/.emacs; \
	fi
	@rsync -av --exclude '.git' emacs.d/ ~/.emacs.d/

check-changes:
	@diff -pruNb --exclude '*~' --exclude '.git' --exclude '*.elc' ~/.emacs.d emacs.d
	@diff -ub ~/.emacs dot.emacs
