complete -c bombadil -n "__fish_use_subcommand" -s h -l help -d 'Print help'
complete -c bombadil -n "__fish_use_subcommand" -s V -l version -d 'Print version'
complete -c bombadil -n "__fish_use_subcommand" -f -a "install" -d 'Link a given dotfile directory settings to "XDG_CONFIG_DIR/bombadil.toml"'
complete -c bombadil -n "__fish_use_subcommand" -f -a "clone" -d 'Install dotfiles from a remote git repository to a target folder'
complete -c bombadil -n "__fish_use_subcommand" -f -a "link" -d 'Symlink a copy of your dotfiles and inject variables according to bombadil.toml settings'
complete -c bombadil -n "__fish_use_subcommand" -f -a "unlink" -d 'Remove all symlinks defined in your bombadil.toml'
complete -c bombadil -n "__fish_use_subcommand" -f -a "watch" -d 'Watch dotfiles and automatically run link on changes'
complete -c bombadil -n "__fish_use_subcommand" -f -a "add-secret" -d 'Add a secret var to bombadil environment'
complete -c bombadil -n "__fish_use_subcommand" -f -a "get" -d 'Get metadata about dots, hooks, path, profiles, or vars'
complete -c bombadil -n "__fish_use_subcommand" -f -a "generate-completions" -d 'Generate shell completions Generate shell completions'
complete -c bombadil -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bombadil -n "__fish_seen_subcommand_from install" -s h -l help -d 'Print help'
complete -c bombadil -n "__fish_seen_subcommand_from clone" -s r -l remote -d 'Remote repository address, either http or ssh' -r
complete -c bombadil -n "__fish_seen_subcommand_from clone" -s t -l target -d 'Target destination, repository name by default' -r -F
complete -c bombadil -n "__fish_seen_subcommand_from clone" -s p -l profiles -d 'A list of comma separated profiles to activate' -r
complete -c bombadil -n "__fish_seen_subcommand_from clone" -s h -l help -d 'Print help'
complete -c bombadil -n "__fish_seen_subcommand_from link" -s p -l profiles -d 'A list of comma separated profiles to activate' -r -f -a "{linux_laptop	,macos	}"
complete -c bombadil -n "__fish_seen_subcommand_from link" -s h -l help -d 'Print help'
complete -c bombadil -n "__fish_seen_subcommand_from unlink" -s h -l help -d 'Print help'
complete -c bombadil -n "__fish_seen_subcommand_from watch" -s p -l profiles -d 'A list of comma separated profiles to activate' -r -f -a "{linux_laptop	,macos	}"
complete -c bombadil -n "__fish_seen_subcommand_from watch" -s h -l help -d 'Print help'
complete -c bombadil -n "__fish_seen_subcommand_from add-secret" -s k -l key -d 'Key of the secret variable to create' -r
complete -c bombadil -n "__fish_seen_subcommand_from add-secret" -s v -l value -r
complete -c bombadil -n "__fish_seen_subcommand_from add-secret" -s f -l file -d 'Path of the var file to modify' -r
complete -c bombadil -n "__fish_seen_subcommand_from add-secret" -s a -l ask -d 'Get the secret value from stdin'
complete -c bombadil -n "__fish_seen_subcommand_from add-secret" -s h -l help -d 'Print help'
complete -c bombadil -n "__fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c bombadil -n "__fish_seen_subcommand_from generate-completions" -s h -l help -d 'Print help'
complete -c bombadil -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from clone; and not __fish_seen_subcommand_from link; and not __fish_seen_subcommand_from unlink; and not __fish_seen_subcommand_from watch; and not __fish_seen_subcommand_from add-secret; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from generate-completions; and not __fish_seen_subcommand_from help" -f -a "install" -d 'Link a given dotfile directory settings to "XDG_CONFIG_DIR/bombadil.toml"'
complete -c bombadil -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from clone; and not __fish_seen_subcommand_from link; and not __fish_seen_subcommand_from unlink; and not __fish_seen_subcommand_from watch; and not __fish_seen_subcommand_from add-secret; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from generate-completions; and not __fish_seen_subcommand_from help" -f -a "clone" -d 'Install dotfiles from a remote git repository to a target folder'
complete -c bombadil -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from clone; and not __fish_seen_subcommand_from link; and not __fish_seen_subcommand_from unlink; and not __fish_seen_subcommand_from watch; and not __fish_seen_subcommand_from add-secret; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from generate-completions; and not __fish_seen_subcommand_from help" -f -a "link" -d 'Symlink a copy of your dotfiles and inject variables according to bombadil.toml settings'
complete -c bombadil -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from clone; and not __fish_seen_subcommand_from link; and not __fish_seen_subcommand_from unlink; and not __fish_seen_subcommand_from watch; and not __fish_seen_subcommand_from add-secret; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from generate-completions; and not __fish_seen_subcommand_from help" -f -a "unlink" -d 'Remove all symlinks defined in your bombadil.toml'
complete -c bombadil -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from clone; and not __fish_seen_subcommand_from link; and not __fish_seen_subcommand_from unlink; and not __fish_seen_subcommand_from watch; and not __fish_seen_subcommand_from add-secret; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from generate-completions; and not __fish_seen_subcommand_from help" -f -a "watch" -d 'Watch dotfiles and automatically run link on changes'
complete -c bombadil -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from clone; and not __fish_seen_subcommand_from link; and not __fish_seen_subcommand_from unlink; and not __fish_seen_subcommand_from watch; and not __fish_seen_subcommand_from add-secret; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from generate-completions; and not __fish_seen_subcommand_from help" -f -a "add-secret" -d 'Add a secret var to bombadil environment'
complete -c bombadil -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from clone; and not __fish_seen_subcommand_from link; and not __fish_seen_subcommand_from unlink; and not __fish_seen_subcommand_from watch; and not __fish_seen_subcommand_from add-secret; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from generate-completions; and not __fish_seen_subcommand_from help" -f -a "get" -d 'Get metadata about dots, hooks, path, profiles, or vars'
complete -c bombadil -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from clone; and not __fish_seen_subcommand_from link; and not __fish_seen_subcommand_from unlink; and not __fish_seen_subcommand_from watch; and not __fish_seen_subcommand_from add-secret; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from generate-completions; and not __fish_seen_subcommand_from help" -f -a "generate-completions" -d 'Generate shell completions Generate shell completions'
complete -c bombadil -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from clone; and not __fish_seen_subcommand_from link; and not __fish_seen_subcommand_from unlink; and not __fish_seen_subcommand_from watch; and not __fish_seen_subcommand_from add-secret; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from generate-completions; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
