# Nord Night Shaleh

# This is the nord-night background with the standard nord colors otherwise.
#
inherits = 'nord'

# This fixes bracket match highlighting.
"ui.cursor.match" = { fg = "nord8", bg = "nord3" }

[palette]
nord0 = '#202428'
nord4 = '#C0C5CF'
